# Generated by Django 3.1.4 on 2020-12-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_contact_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='username',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
